/** Indian states & UTs — placeholders for affiliation directory */
export const affiliatedStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar",
  "Chandigarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
  // Extra association slots for 48+ directory capacity
  "Maharashtra — Konkan Zone",
  "Maharashtra — Pune Zone",
  "Maharashtra — Vidarbha Zone",
  "Maharashtra — Marathwada Zone",
  "Gujarat — North Zone",
  "Gujarat — South Zone",
  "Karnataka — North Zone",
  "Karnataka — South Zone",
  "Madhya Pradesh — West Zone",
  "Rajasthan — East Zone",
  "Uttar Pradesh — West Zone",
  "Tamil Nadu — West Zone",
].map((name, i) => ({
  id: i + 1,
  name,
  status: i < 28 ? ("Affiliated" as const) : ("Provisional" as const),
  members: 40 + ((i * 17) % 120),
}));
